### ISSUE TITLE
页面端如何显示RN组件

### ISSUE THREAD

**Issue by PLDaily** [blankapp/ui#12]
你好，我想问下该UI的文档页面是如何显示RN的组件的。即这个页面 [https://uiexplorer.blankapp.org/](https://uiexplorer.blankapp.org/)是怎么生成的?

**Comment by lijy91** [comment]
是用 [react-native-web](https://github.com/necolas/react-native-web) 对 React Native 进行的 Web 支持，你可以使用 https://github.com/blankapp/react-native-template-ui-based 这个模板创建你的跨三端项目。

**Comment by PLDaily** [comment]
OK，多谢
