### ISSUE TITLE
RNTouchableOpacity throws TypeError: Cannot read property 'opacity' of undefined

### ISSUE THREAD

**Issue by levinqdl** [blankapp/ui#13]
RNTouchableOpacity throws TypeError: Cannot read property 'opacity' of undefined when style prop not provided

**Comment by levinqdl** [comment]
我看了一下 RN 的 TouchableOpacity 的代码，现在已经没有用到 setNativeProps 了，而且用所以是不是我们不再需要封装这个组件了，直接导出 RN 的 TouchableOpacity 使用即可？

**Comment by lijy91** [comment]
使用 setNativeProps 的原因是因为 TouchableOpacity 直接修改 style 的 opacity 属性无法生效，导致 withStyles 方法不能正常工作

**Comment by lijy91** [comment]
81fff2c02281775d8bda7d41f287dedbedec7022 Fixed.
